---
linux: #Группа хостов 
  children: #Обозначение, что будет подгруппа хостов
    nginx_proxy: #Имя подгруппы хостов
      hosts: #Узлы группы
        vm_1: #Имя машины
          ansible_host: 158.160.56.19 #Адрес машины
    nginx_custom: #Имя подгруппы хостов
      hosts: #Узлы группы
        vm_2:
          ansible_host: 51.250.11.176
        vm_3:
          ansible_host: 158.160.40.180

  vars: #Переменные, доступные или используемые для всех подгрупп
    ansible_user: "root"
    ansible_become: false #Становиться ли другим пользователем после подключения
